spring.application.name=ms_usuario
server.port=8081

# Swagger
debug=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/doc/v3/api-docs
springdoc.swagger-ui.path=/doc/swagger-ui.html

# Perfil activo por defecto
spring.profiles.active=dev