spring:
  application:
    name: ms_inventario

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
#Para evitar problemas de hostname
  instance:
    prefer-ip-address: true