# ✅ MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/ms_pedidos
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ✅ JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ✅ LOGS
logging.file.name=logs/ms_pedidos.log
logging.level.root=INFO
logging.level.com.example.ms_pedidos=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# ✅ SEGURIDAD
spring.security.user.name=admin
spring.security.user.password=admin123