spring:
  application:
    name: ms_proveedores

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#Para evitar problemas de hostname
  instance:
    prefer-ip-address: true